void display(){

  temp_internal = dht21.readTemperature();
  temp_external = dht22.readTemperature();
  hum_internal = dht21.readHumidity();
  hum_external = dht22.readHumidity(); 
  ldr = analogRead(light);
  Carbon = analogRead(InputCo2); 
  int ValueCo2 = Carbon-255;
  int co2good = map(Carbon, 0, 1024, 400, 5000);    
  soil1 = analogRead(sensor1);
  pre1 = map(soil1, wet_sensor1, dry_sensor1, 100, 0);
  soil2 = analogRead(sensor2);
  pre2 = map(soil2, wet_sensor2, dry_sensor2, 100, 0);
  soil3 = analogRead(sensor3);
  pre3 = map(soil3, wet_sensor3, dry_sensor3, 100, 0);
  soil4 = analogRead(sensor4);
  pre4 = map(soil4, wet_sensor4, dry_sensor4, 100, 0);        
  tft.setCursor(0, 0);
  tft.setTextColor(WHITE);  
  tft.setTextSize(2);
  tft.println(" GREENHOUSE AUTOMATION");
  tft.setTextColor(BLUE); 
  tft.setTextSize(2);
  tft.println("  Sensors Reading");
  tft.setTextColor(YELLOW);   
  tft.setTextSize(2);
  tft.print("T_in:");
  tft.print(temp_internal);
  tft.println(" *C");
  tft.print("H_in:");
  tft.print(hum_internal);
  tft.println(" %");
  tft.setTextColor(BLUE);
  tft.setTextSize(2);
  tft.print("T_ex:");
  tft.print(temp_external);
  tft.println(" *C");
  tft.print("H_ex:");
  tft.print(hum_external);
  tft.println(" %");
  tft.setTextColor(YELLOW);
  tft.setTextSize(2);
  tft.print("LDR:");
  tft.println(ldr);
  tft.setTextColor(YELLOW);
  tft.setTextSize(2);
  tft.print("MOist1:");
  tft.print(pre1);
  tft.println(" %");
  tft.setTextColor(YELLOW);
  tft.setTextSize(2);
  tft.print("MOist2:");
  tft.print(pre2);
  tft.println(" %");
  tft.setTextColor(YELLOW);
  tft.setTextSize(2);
  tft.print("MOist3:");
  tft.print(pre3);
  tft.println(" %");
  tft.setTextColor(YELLOW);
  tft.setTextSize(2);
  tft.print("MOist4:");
  tft.print(pre4);
  tft.println(" %");
  tft.setTextColor(BLUE);
  tft.setTextSize(2);
  tft.print("C02:");
  tft.print(co2good);
  tft.println(" RPM");    
  manytimes++;
  total++;
  if (manytimes == 50) {
    tft.fillScreen(BLACK);
    manytimes = 0;
  }
  delay(kath);
  tft.setTextSize(1);
  tft.fillRect(50, 80, 128, 40, BLACK);
  tft.setTextColor(WHITE);
}